name: flutter_lechuzo_integradora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  flutter_custom_tabs: ^1.2.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logoIntegradora.png

# ✅ CORRECCIÓN: Esto va AQUÍ AFUERA (al mismo nivel que 'flutter', no adentro)
flutter_native_splash:
  color: "#FEF8D8"
  image: assets/logoIntegradora.png
  android_12:
    color: "#FEF8D8"
    image: assets/logoIntegradora.png